//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleWF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class concepto
    {
        public int id { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> importe { get; set; }
    
        public virtual venta venta { get; set; }
    }
}
